spring:
  datasource:
    url: "jdbc:mysql://autenticacion-biometrica-test.cuhwiikx8iqy.us-east-1.rds.amazonaws.com:3306/quipux"
    username: admin
    password: yoqYSY971
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
